---
- name: ver resultados de hostnames
  hosts: all
  vars:
    fichero: "{{ lookup ('file', './resultados.json') | from_json }}"
  tasks:
    - name: Obtengo fichero
      debug:
        var: fichero

    - name: debug de valor del from_json
      debug:
        msg: "{{ fichero.vm_list_result.json  }}"

    - name: Obtener el hostname y memory
      debug:
        msg: "El hostname es {{ item.hostname }} y la memoria {{ item.memory }} "
      loop: "{{ fichero.vm_list_result.json }}"
